### PR TITLE
update to version 1.6.2.0

### PR DESCRIPTION
**Pull request by mimmi20**

### CODE REVIEW

**Comment by slashmili** [comment]
Thomas,

Can you fix the tests?

**Comment by mimmi20** [comment]
@slashmili The tests are fixed now. I also added the test support for PHP 7 on travis-ci.

**Comment by slashmili** [comment]
Thanks

**Comment by slashmili** [comment]
I've pushed the tag `1.6.2.0`

**Comment by mimmi20** [comment]
Thanks

**Pull request merged**
